#---
#- hosts: all
#  become: true
  
#  tasks:
#    - name: update apt packages
#      apt:
#        upgrade: yes
#        update_cache: yes


---
- hosts: all
  become: true
#  become_method: su
  
  tasks:

   # - name: packages | ensure apt list dir exists
   #   file:
   #     path: /var/lib/apt/lists/
   #     state: directory
   #     mode: 0755

    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all packages on servers
      apt: upgrade=dist force_apt_get=yes

    - name: Check if a reboot is needed on all servers
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no

    - name: Reboot the box if kernel updated
      reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists

    - pushover:
        msg: '{{ inventory.hostname }} has been patched successfully'
        app_token: axoxckp9c1qytuw3g3q5qqsyzpq8s7
        user_key: uyxc83ns5g48w4rxbdpqqyqxz6w8ae
      delegate_to: localhost